### ISSUE TITLE
Formatting Issue

### ISSUE THREAD

**Issue by G-dogger** [marioloncarek/megamenu-js#10]
Hi, I'm loving this menu so far! Great Job! But I can't figure out how to adjust the height of the main nav bar. There is a lot of padding above and below the text. I need a large font but not so much vertical spacing. I'm assuming it's something simple in the style.css but I can't figure it out. Thanks so much!

Scott

**Comment by marioloncarek** [comment]
Please take a look at the padding on line 102 in this example: http://codepen.io/riogrande/pen/MKXweV - thats how you control the height. Please comment if you have more questions

**Comment by G-dogger** [comment]
I found it, thank you!
