### ISSUE TITLE
Follow-up to Formatting Question

### ISSUE THREAD

**Issue by G-dogger** [marioloncarek/megamenu-js#11]
Is there a way to change font color of the sub/sub list items to differentiate them from their sub headings?

Thanks again!

Scott

**Comment by marioloncarek** [comment]
Please look at the line 137 http://codepen.io/riogrande/pen/MKXweV - you change the color of "a" . Please ask if you have more questions

**Comment by G-dogger** [comment]
Okay, thanks again!
