### ISSUE TITLE
Question: how to embed megamenu into table

### ISSUE THREAD

**Issue by mistergibson** [marioloncarek/megamenu-js#34]
I was wondering about embedding the megamenu within a table. I want a menu with a logo on the far left, divs above and below the menu and the nearest I can figure it so attempt to embed the menu w/ a table-cell or some such. If you have any tips for attempting this, or know of an easier way please let me know as at this point any advice is welcome. In a prior question I was interested in something similar, but I'm wondering if this approach is what you'd advise.

Thanks in advance,

G.

**Comment by marioloncarek** [comment]
you should learn about css layouts, as your question is very general.
