### ISSUE TITLE
Question: how to reduce the size of the menu vertically?

### ISSUE THREAD

**Issue by mistergibson** [marioloncarek/megamenu-js#35]
I have the menu *almost* working perfectly. However, I'm neither a JavaScript nor CSS expert and am having trouble finding *exactly* where in the CSS/etc to make changes to reduce the vertical size of the main menu itself. Any advice is welcome.

Thanks,

G.

**Comment by marioloncarek** [comment]
try changing the padding on this element `.menu > ul > li a`. if this is not what you were looking for please re-open
