### ISSUE TITLE
Dropdown bug

### ISSUE THREAD

**Issue by mateitudor** [marioloncarek/megamenu-js#4]
Hi Mario,
So when a user clicks to open a few submenus but then resizes the window, the dropdowns remain open one on top of the other, and there is a weird flicker and backwards behaviour.

Any idea why?
Attached a .gif so you can see what I mean.

Would appreciate an answer. Thank you.
![megamenu-dropdown-bug](https://cloud.githubusercontent.com/assets/1410849/16102367/66e4cc5a-3377-11e6-9af2-43043a6a8db9.gif)

**Comment by marioloncarek** [comment]
Let me look at this today and bring you soutluon. Thanks for using megamenu.js!

**Comment by mateitudor** [comment]
Thank you for answering, sir. And quite hopeful that we can fix this little bug.

Thanks!

**Comment by marioloncarek** [comment]
Hello friend! A simple on resize event is all you need for this fix : 

```
$(window).resize(function() {
  $(".menu > ul > li").children("ul").hide();
  $(".menu > ul").removeClass('show-on-mobile');
});
```

And working demo is at: http://codepen.io/riogrande/pen/gMMdRa

Please, let me know if you have any more questions before i close! Thanks

**Comment by mateitudor** [comment]
It works! Perfect. Thank you so much, sir. You can close it now.

**Comment by jshepdevelopment** [comment]
This solution is working. Thanks!

**Comment by marioloncarek** [comment]
No problem m8s
