### ISSUE TITLE
Omit the "Navigation" label on the menu bar

### ISSUE THREAD

**Issue by krwickliffe** [marioloncarek/megamenu-js#9]
I'd like to get rid of the "Navigation" word that shows up on the left side of the menu bar in responsive view, but I can't figure out where this is being defined. Not finding it in the html or the CSS. Any help is appreciated, thanks!

Nevermind!
I just found it in the megamenu.js - Should have looked around more before commenting. Thanks!
;0)

**Comment by marioloncarek** [comment]
In megamenu.js, on line 13 you can change it to what ever you like! 
Thanks for using my plugin. Im gonna close this issues.
